ALTER TABLE companies ADD COLUMN IF NOT EXISTS address    TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS phone      TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS logo_data  TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS cover_data TEXT;
